### ISSUE TITLE
Mapping from PSR-3 context to watchdog variables

### ISSUE THREAD

**Issue by kasperg** [drupol/drupal7_psr3_watchdog#1]
Thanks for publishing this, I tried this out in a project and ran into problems with with mapping from the PSR-3 `$context` array to watchdog `$variables` array.

The current implementation seems to assume that the context will also contain be empty or an array with keys `variables` and/or `link`.

However if the context has any other keys the following line will force variables and link to be the first entry of the context. These may not be arrays or keys at all.

This causes problems down the line.

For example [`syslog_watchdog()`](https://api.drupal.org/api/drupal/modules%21syslog%21syslog.module/function/syslog_watchdog/7.x) uses the variables array for [`strtr()`](http://php.net/manual/en/function.strtr.php) which will return `false`  and thus produce an empty log message.

I know this is early days but you just happen to release this at a time where I was looking for a  PSR-3 adapter for Drupal 7. The existing ones do not look good and I was excited to find a library by you 😄 .

On another note: You might want to consider renaming the library. `watchdog` does not necessarily mean `dblog`.

**Comment by drupol** [comment]
Hey Kasper!

Long time no see mate !

I had most of your comment in mind and I've updated the library accordingly, just now.

I've also renamed the repository to `drupal7_psr3_watchdog`, it makes more sense indeed.

Let me know if it's better now 😄

**Comment by kasperg** [comment]
Yes - long time, no see 😄 .

As far as I can tell the situation is the same as the [`WatchdogLogger->log()`](https://github.com/drupol/drupal7_psr3_watchdog/blob/master/src/Logger/WatchdogLogger.php#L49) method is about the same.

An example of what causes the problem:

```php
$logger = new WatchdogLogger('custom');
$logger->log(LogLevel::NOTICE, "The message",['foo' => 1, `bar`=> [42]]);
```

This means that in [the assignment of the `$variables` and `$link` variables](https://github.com/drupol/drupal7_psr3_watchdog/blob/master/src/Logger/WatchdogLogger.php#L49) will not contain values that make sense:

```php
list($variables, $link) = array_values(['foo' => 1, 'bar' => [42]] + ['variables' => [], 'link' => '']);
// $variables == 1,
// $link ==  [42]
```

Having `$variables` not be an array of token/replacement values will cause these problems.

I would have expected:

```php
$variables = [
  'foo' => 1
  'bar' => [42]
];
$link = '';
```

**Comment by drupol** [comment]
Indeed, I see the issue.

Fix coming today, I'll post in here as soon as it's ready.

**Comment by drupol** [comment]
@kasperg Is it better now ?

**Comment by drupol** [comment]
I will also implement this: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#12-message

**Comment by drupol** [comment]
Ok I think it's ready, could you check now ?

**Comment by kasperg** [comment]
@drupol: :+1: Thanks a bunch. Occupied with other stuff now but I will take a look at it next week.

**Comment by drupol** [comment]
Cool! Waiting for your feedback before tagging :-)

**Comment by drupol** [comment]
Got news for me @kasperg ?

**Comment by kasperg** [comment]
Works for me now. Great! I think it is ready for tagging.

A few other thoughts:

- Currently [the logger just returns if `watchdog()` is not defined](https://github.com/drupol/drupal7_psr3_watchdog/blob/master/src/Handler/Drupal7Watchdog.php#L17). It smells a bit like failing silently to me. How about throwing an exception instead?
- I am not using this library with Composer but with Drush Make, Libraries API and X Autoload. With this combo I am having problems with autoloading. The library only seems to be registered if I download this library to a folder with `-` replacing `_` 😑 .
- `formatRecord()` is getting complex. A unit test would be nice.

**Comment by drupol** [comment]
Ok good news.

1: Ok I've fixed it, it returns a simple \Exception() if `watchdog()` is not found.
2: This is not the issue of this library, maybe debugging why XAutoload is not able to register the classes might be better. Is there someone else who already had the issue on d.o. ?
3) I'm thinking about it, I think I will add PHPSpec tests very soon.

In the meantime, I will tag 0.0.2.

**Comment by kasperg** [comment]
:+1:

**Comment by drupol** [comment]
Tests are in :-)
